language: python
python:
  - "2.7"
install:
  - "pip install -e .[dev]"
before_script:
  # Lint the Python code.
  - "flake8 ."
script:
  # Run all discoverable tests
  - "sudo py.test --cov=tasker"
after_success:
  # Sends the coverage report to coveralls.io which can report to Pull Requests
  # and track test coverage over time.
  - "coveralls"
cache: pip